import json

# 질문과 답변 리스트
questions = ["SELECT bank_nm, acct_dv, acct_no, acct_bal_amt, open_dt, due_dt, intr_rate, acct_bal_upd_dtm FROM aicfo_get_all_amt WHERE view_dv = '대출' AND curr_cd = 'KRW' AND reg_dt = '20240505'",
"SELECT bank_nm, acct_dv, acct_no, acct_bal_amt, real_amt, acct_bal_upd_dtm FROM aicfo_get_all_amt WHERE view_dv = '수시' AND curr_cd = 'KRW' AND acct_dv LIKE '%kdb뉴딜%' AND reg_dt = '20240818'",
"SELECT bank_nm, acct_no, curr_cd, deposit_foreign, total_appr_amt, real_amt, acct_bal_upd_dtm FROM aicfo_get_all_amt WHERE view_dv = '증권' AND reg_dt = '20240520' and curr_cd <> 'KRW'",
"SELECT bank_nm, acct_no, curr_cd, deposit_foreign, total_appr_amt, real_amt, acct_bal_upd_dtm FROM aicfo_get_all_amt WHERE view_dv = '증권' AND reg_dt = '20240919' and curr_cd <> 'KRW'",
"SELECT bank_nm, acct_no, curr_cd, deposit_foreign, total_appr_amt, real_amt, acct_bal_upd_dtm FROM aicfo_get_all_amt WHERE view_dv = '증권' AND reg_dt = '20240513' and curr_cd <> 'KRW'",
"SELECT bank_nm, acct_dv, acct_no, acct_bal_amt, real_amt, acct_bal_upd_dtm FROM aicfo_get_all_amt WHERE view_dv = '수시' AND curr_cd = 'KRW' AND bank_nm = '신한은행' AND acct_bal_amt <> 0 AND reg_dt = '20240630'",
"SELECT bank_nm, acct_dv, acct_no, acct_bal_amt, real_amt, acct_bal_upd_dtm FROM aicfo_get_all_amt WHERE view_dv = '수시' AND curr_cd = 'KRW' AND acct_bal_amt <> 0 AND reg_dt = '20240812'",
"SELECT bank_nm, acct_no, curr_cd, deposit_foreign, total_appr_amt, real_amt, acct_bal_upd_dtm FROM aicfo_get_all_amt WHERE view_dv = '증권' AND curr_cd = 'USD' AND reg_dt = '20250515'",
"SELECT bank_nm, acct_no, curr_cd, deposit_foreign, total_appr_amt, real_amt, acct_bal_upd_dtm FROM aicfo_get_all_amt WHERE view_dv = '증권' AND curr_cd = 'USD' AND reg_dt = '20240927'",
"SELECT bank_nm, acct_dv, acct_no, acct_bal_amt, real_amt, acct_bal_upd_dtm FROM aicfo_get_all_amt WHERE view_dv = '수시' AND curr_cd = 'KRW' AND bank_nm = '구)외환은행' AND reg_dt = '20240827'",
"SELECT bank_nm, acct_dv, acct_no, acct_bal_amt, real_amt, acct_bal_upd_dtm FROM aicfo_get_all_amt WHERE view_dv = '수시' AND curr_cd = 'KRW' AND bank_nm = '구)외환은행' AND reg_dt = '20250915'",
"SELECT bank_nm, acct_dv, acct_no, acct_bal_amt, real_amt, acct_bal_upd_dtm FROM aicfo_get_all_amt WHERE view_dv = '수시' AND curr_cd = 'KRW' AND bank_nm = '기업은행' AND acct_bal_amt = 0 AND reg_dt = '20241016'",
"SELECT bank_nm, acct_dv, acct_no, acct_bal_amt, real_amt, acct_bal_upd_dtm FROM aicfo_get_all_amt WHERE view_dv = '수시' AND curr_cd = 'KRW' AND acct_bal_amt = 0 AND reg_dt = '20240921'",
"SELECT bank_nm, acct_dv, acct_no, acct_bal_amt, real_amt, acct_bal_upd_dtm FROM aicfo_get_all_amt WHERE view_dv = '수시' AND curr_cd = 'KRW' AND acct_bal_amt = 0 AND reg_dt = '20250630'",
"SELECT bank_nm, acct_dv, acct_no, acct_bal_amt, real_amt, acct_bal_upd_dtm FROM aicfo_get_all_amt WHERE view_dv = '수시' AND curr_cd = 'KRW' AND acct_bal_amt = 0 AND reg_dt = '20250213'",
"SELECT bank_nm, acct_no, deposit_amt, total_appr_amt, acct_bal_amt, acct_bal_upd_dtm FROM aicfo_get_all_amt WHERE view_dv = '증권' AND curr_cd = 'KRW' AND bank_nm = '삼성증권' AND reg_dt = '20240821'",
"SELECT bank_nm, COUNT(*) AS acct_cnt FROM aicfo_get_all_amt WHERE view_dv = '수시' AND curr_cd = 'KRW' AND reg_dt = '20240817' GROUP BY bank_nm",
"SELECT bank_nm, COUNT(*) AS acct_cnt FROM aicfo_get_all_amt WHERE view_dv = '예적금' AND curr_cd = 'KRW' AND reg_dt = '20241020' GROUP BY bank_nm",
"SELECT bank_nm, COUNT(*) AS acct_cnt FROM aicfo_get_all_amt WHERE view_dv = '수시' AND curr_cd <> 'KRW' AND reg_dt = '20240905' GROUP BY bank_nm",
"SELECT bank_nm, COUNT(*) AS acct_cnt FROM aicfo_get_all_amt WHERE view_dv = '증권' AND curr_cd = 'KRW' AND reg_dt = '20240802' GROUP BY bank_nm",
"SELECT bank_nm, acct_dv, acct_no, acct_bal_amt, real_amt, acct_bal_upd_dtm FROM aicfo_get_all_amt WHERE view_dv = '수시' AND curr_cd = 'KRW' AND reg_dt = '20240131'",
"SELECT bank_nm, acct_dv, acct_no, acct_bal_amt, real_amt, acct_bal_upd_dtm FROM aicfo_get_all_amt WHERE view_dv = '수시' AND curr_cd = 'KRW' AND reg_dt = '20240308'",
"SELECT bank_nm, acct_dv, acct_no, acct_bal_amt, real_amt, acct_bal_upd_dtm FROM aicfo_get_all_amt WHERE view_dv = '수시' AND curr_cd = 'KRW' AND reg_dt = '20240405'",
"SELECT bank_nm, COUNT(acct_no) AS account_count FROM aicfo_get_all_amt WHERE view_dv = '예적금' AND curr_cd = 'KRW' AND reg_dt = '20241001' GROUP BY bank_nm ORDER BY account_count DESC",
"SELECT bank_nm, COUNT(acct_no) AS account_count FROM aicfo_get_all_amt WHERE view_dv = '예적금' AND curr_cd = 'KRW' AND reg_dt = '20241110' GROUP BY bank_nm ORDER BY account_count DESC",
"SELECT bank_nm, COUNT(*) AS acct_cnt FROM aicfo_get_all_amt WHERE view_dv = '수시' AND curr_cd = 'KRW' AND bank_nm = '우리은행' AND reg_dt = '20240619' GROUP BY bank_nm",
"SELECT bank_nm, COUNT(*) AS acct_cnt FROM aicfo_get_all_amt WHERE view_dv = '수시' AND curr_cd = 'KRW' AND bank_nm = '국민은행' AND reg_dt = '20240928' GROUP BY bank_nm",
"SELECT bank_nm, acct_no, acct_dv, acct_bal_amt, open_dt, due_dt, intr_rate, acct_bal_upd_dtm FROM aicfo_get_all_amt WHERE view_dv = '예적금' AND curr_cd = 'KRW' AND acct_bal_amt BETWEEN (1 * POWER(10, 11) * 0.9) AND (1 * POWER(10, 11) * 1.1) AND reg_dt = '20251101'",
"SELECT bank_nm, acct_no, curr_cd, acct_bal_amt, acct_dv, total_prchs_amt, total_appr_amt, return_rate, deposit_foreign, acct_bal_amt, deposit_amt, acct_bal_upd_dtm FROM aicfo_get_all_amt WHERE view_dv = '증권' AND curr_cd = 'KRW' AND reg_dt = '20251101' AND acct_bal_amt BETWEEN (7 * POWER(10, 11)) AND ((7 + 1) * POWER(10, 11) - 1)",
"SELECT bank_nm, acct_no, curr_cd, acct_bal_amt, acct_dv, total_prchs_amt, total_appr_amt, return_rate, deposit_foreign, acct_bal_amt, deposit_amt, acct_bal_upd_dtm FROM aicfo_get_all_amt WHERE view_dv = '증권' AND curr_cd = 'KRW' AND reg_dt = '20251105' AND acct_bal_amt BETWEEN (8 * POWER(10, 9) * 0.9) AND (8 * POWER(10, 9) * 1.1)",
"SELECT bank_nm, acct_no, curr_cd, acct_bal_amt, acct_dv, total_prchs_amt, total_appr_amt, return_rate, deposit_foreign, acct_bal_amt, deposit_amt, acct_bal_upd_dtm FROM aicfo_get_all_amt WHERE view_dv = '증권' AND curr_cd = 'KRW' AND reg_dt = '20251105' AND acct_bal_amt BETWEEN (8 * POWER(10, 9) * 0.9) AND (8 * POWER(10, 9) * 1.1)",
"SELECT bank_nm, acct_no, acct_dv, acct_bal_amt, open_dt, due_dt, intr_rate, acct_bal_upd_dtm FROM aicfo_get_all_amt WHERE view_dv = '대출' AND curr_cd = 'KRW' AND acct_bal_amt BETWEEN (5 * POWER(10, 10)) AND ((5 + 1) * POWER(10, 10) - 1) AND reg_dt = '20250202'",
"SELECT bank_nm, acct_no, acct_dv, acct_bal_amt, open_dt, due_dt, intr_rate, acct_bal_upd_dtm FROM aicfo_get_all_amt WHERE view_dv = '대출' AND curr_cd = 'KRW' AND acct_bal_amt BETWEEN (5 * POWER(10, 10)) AND ((5 + 1) * POWER(10, 10) - 1) AND reg_dt = '20250202'",
"SELECT bank_nm, acct_dv, acct_no, acct_bal_amt, open_dt, due_dt, intr_rate, acct_bal_upd_dtm FROM aicfo_get_all_amt WHERE view_dv = '예적금' AND curr_cd = 'KRW' AND acct_no LIKE '%2105%' AND reg_dt = '20241219'",
"SELECT bank_nm, acct_dv, acct_no, acct_bal_amt, open_dt, due_dt, intr_rate, acct_bal_upd_dtm FROM aicfo_get_all_amt WHERE view_dv = '대출' AND curr_cd = 'KRW' AND acct_no LIKE '%4651%' AND reg_dt = '20240909'",
"SELECT bank_nm, acct_dv, acct_no, curr_cd, acct_bal_amt, real_amt, acct_bal_upd_dtm FROM aicfo_get_all_amt WHERE view_dv = '수시' AND curr_cd <> 'KRW' AND acct_no LIKE '%4415%' AND reg_dt = '20241016'",
"SELECT bank_nm, acct_dv, acct_no, curr_cd, acct_bal_amt, real_amt, acct_bal_upd_dtm FROM aicfo_get_all_amt WHERE view_dv = '수시' AND curr_cd <> 'KRW' AND reg_dt = '20241109' AND acct_bal_amt <> 0",
"SELECT bank_nm, acct_no, deposit_amt, total_appr_amt, acct_bal_amt, acct_bal_upd_dtm FROM aicfo_get_all_amt WHERE view_dv = '증권' AND curr_cd = 'KRW' AND reg_dt = '20241023' AND acct_bal_amt <> 0",
"SELECT bank_nm, acct_dv, acct_no, acct_bal_amt, real_amt, acct_bal_upd_dtm FROM aicfo_get_all_amt WHERE view_dv = '수시' AND curr_cd = 'KRW' AND acct_no LIKE '%100037340220%' AND reg_dt = '20241023'",
"SELECT bank_nm, acct_dv, acct_no, acct_bal_amt, open_dt, due_dt, intr_rate, acct_bal_upd_dtm FROM aicfo_get_all_amt WHERE view_dv = '예적금' AND curr_cd = 'KRW' AND acct_no LIKE '%28491002652105%' AND reg_dt = '20240915'",
"SELECT bank_nm, acct_dv, acct_no, acct_bal_amt, real_amt, acct_bal_upd_dtm FROM aicfo_get_all_amt WHERE view_dv = '수시' AND curr_cd = 'KRW' AND reg_dt = '20250205' AND acct_bal_amt >= POWER(10,8)",
"SELECT bank_nm, acct_dv, acct_no, acct_bal_amt, open_dt, due_dt, intr_rate, acct_bal_upd_dtm FROM aicfo_get_all_amt WHERE view_dv = '예적금' AND curr_cd = 'KRW' AND reg_dt = '20240722' AND acct_bal_amt >= POWER(10,8)",
"SELECT bank_nm, acct_no, deposit_amt, total_appr_amt, acct_bal_amt, acct_bal_upd_dtm FROM aicfo_get_all_amt WHERE view_dv = '증권' AND curr_cd = 'KRW' AND reg_dt = '20240706' AND acct_bal_amt >= POWER(10,8)",
"SELECT bank_nm, acct_dv, acct_no, acct_bal_amt, open_dt, due_dt, intr_rate, acct_bal_upd_dtm FROM aicfo_get_all_amt WHERE view_dv = '예적금' AND curr_cd = 'KRW' AND reg_dt = '20241202'",
"SELECT bank_nm, acct_dv, acct_no, acct_bal_amt, open_dt, due_dt, intr_rate, acct_bal_upd_dtm FROM aicfo_get_all_amt WHERE view_dv = '대출' AND curr_cd = 'KRW' AND reg_dt = '20240715'",
"SELECT bank_nm, acct_dv, acct_no, curr_cd, acct_bal_amt, real_amt, acct_bal_upd_dtm FROM aicfo_get_all_amt WHERE view_dv = '수시' AND curr_cd <> 'KRW' AND reg_dt = '20240707'",
"SELECT bank_nm, acct_no, deposit_amt, total_appr_amt, acct_bal_amt, acct_bal_upd_dtm FROM aicfo_get_all_amt WHERE view_dv = '증권' AND curr_cd = 'KRW' AND reg_dt = '20240225'",
"SELECT bank_nm, COUNT(acct_no) AS account_count FROM aicfo_get_all_amt WHERE view_dv = '수시' AND curr_cd = 'KRW' AND reg_dt = '20250122' GROUP BY bank_nm ORDER BY account_count DESC",
"SELECT bank_nm, COUNT(acct_no) AS account_count FROM aicfo_get_all_amt WHERE view_dv = '증권' AND curr_cd = 'KRW' AND reg_dt = '20240815' GROUP BY bank_nm ORDER BY account_count DESC",
"SELECT bank_nm, SUM(acct_bal_amt) AS total_acct_bal_amt FROM aicfo_get_all_amt WHERE view_dv = '수시' AND curr_cd = 'KRW' AND reg_dt = '20240917' GROUP BY bank_nm",
"SELECT bank_nm, SUM(acct_bal_amt) AS total_acct_bal_amt FROM aicfo_get_all_amt WHERE view_dv = '수시' AND curr_cd = 'KRW' AND reg_dt = '20241012' GROUP BY bank_nm",
"SELECT bank_nm, SUM(acct_bal_amt) AS total_acct_bal_amt FROM aicfo_get_all_amt WHERE view_dv = '증권' AND curr_cd = 'KRW' AND reg_dt = '20241223' GROUP BY bank_nm",
"SELECT bank_nm, acct_dv, acct_no, acct_bal_amt, open_dt, due_dt, intr_rate, acct_bal_upd_dtm FROM aicfo_get_all_amt WHERE view_dv = '예적금' AND curr_cd = 'KRW' AND reg_dt = '20240123'",
"SELECT bank_nm, COUNT(*) AS acct_cnt FROM aicfo_get_all_amt WHERE view_dv = '수시' AND curr_cd <> 'KRW' AND bank_nm = '하나은행' AND reg_dt = '20240723' GROUP BY bank_nm",
"SELECT bank_nm, COUNT(*) AS acct_cnt FROM aicfo_get_all_amt WHERE view_dv = '증권' AND curr_cd = 'KRW' AND bank_nm = '삼성증권' AND reg_dt = '20241012' GROUP BY bank_nm",
"SELECT bank_nm, acct_dv, acct_no, acct_bal_amt, open_dt, due_dt, intr_rate, acct_bal_upd_dtm FROM aicfo_get_all_amt WHERE view_dv = '예적금' AND curr_cd = 'KRW' AND reg_dt = '20240123' ORDER BY acct_bal_amt DESC",
"SELECT bank_nm, acct_dv, acct_no, acct_bal_amt, open_dt, due_dt, intr_rate, acct_bal_upd_dtm FROM aicfo_get_all_amt WHERE view_dv = '대출' AND curr_cd = 'KRW' AND reg_dt = '20240202' ORDER BY acct_bal_amt DESC",
"SELECT bank_nm, acct_dv, acct_no, curr_cd, acct_bal_amt, real_amt, acct_bal_upd_dtm FROM aicfo_get_all_amt WHERE view_dv = '수시' AND curr_cd <> 'KRW' AND reg_dt = '20240723' ORDER BY acct_bal_amt DESC",
"SELECT bank_nm, acct_no, deposit_amt, total_appr_amt, acct_bal_amt, acct_bal_upd_dtm FROM aicfo_get_all_amt WHERE view_dv = '증권' AND curr_cd = 'KRW' AND reg_dt = '20240516' ORDER BY acct_bal_amt DESC",
"SELECT bank_nm, acct_dv, acct_no, acct_bal_amt, real_amt, acct_bal_upd_dtm FROM aicfo_get_all_amt WHERE view_dv = '수시' AND curr_cd = 'KRW' AND reg_dt = '20240630'",
"SELECT bank_nm, acct_dv, acct_no, acct_bal_amt, real_amt, acct_bal_upd_dtm FROM aicfo_get_all_amt WHERE view_dv = '수시' AND curr_cd = 'KRW' AND acct_bal_amt >= 10000000 AND reg_dt = '20240123'",
"SELECT view_dv, bank_nm, curr_cd, COUNT(*) AS acct_cnt FROM aicfo_get_all_amt WHERE reg_dt = '20240318' GROUP BY view_dv, bank_nm, curr_cd",
"SELECT bank_nm, acct_dv, acct_no, acct_bal_amt, real_amt, acct_bal_upd_dtm FROM aicfo_get_all_amt WHERE view_dv = '수시' AND curr_cd = 'KRW' AND reg_dt = '20240123' AND acct_bal_amt >= POWER(10,8)",
"SELECT bank_nm, acct_dv, acct_no, acct_bal_amt, real_amt, acct_bal_upd_dtm FROM aicfo_get_all_amt WHERE view_dv = '수시' AND curr_cd = 'KRW' AND acct_dv LIKE '%월급%' AND reg_dt = '20250218'",
"SELECT view_dv, SUM(acct_bal_amt) AS total_acct_bal_amt FROM aicfo_get_all_amt WHERE view_dv IN ('수시', '예적금') AND curr_cd = 'KRW' AND reg_dt = '20240822' GROUP BY view_dv",
"SELECT bank_nm, acct_no, acct_bal_amt, real_amt, acct_bal_upd_dtm FROM aicfo_get_all_amt WHERE view_dv = '수시' AND curr_cd = 'KRW' AND reg_dt = '20250218' AND real_amt >= POWER(10,10)",
"SELECT view_dv, SUM(acct_bal_amt) AS total_acct_bal_amt FROM aicfo_get_all_amt WHERE view_dv IN ('수시', '예적금') AND curr_cd = 'KRW' AND reg_dt = '20240822' GROUP BY view_dv",
"SELECT bank_nm, acct_dv, acct_no, acct_bal_amt, real_amt, acct_bal_upd_dtm FROM aicfo_get_all_amt WHERE view_dv = '수시' AND curr_cd = 'KRW' AND acct_dv LIKE '%월급%' AND reg_dt = '20241220'",
"SELECT view_dv, bank_nm, acct_dv, acct_no, acct_bal_amt, real_amt, acct_bal_upd_dtm FROM aicfo_get_all_amt WHERE view_dv IN ('수시', '예적금', '대출', '증권') AND curr_cd = 'KRW' AND reg_dt = '20241220'",
"SELECT bank_nm, acct_dv, acct_no, deposit_amt, total_appr_amt, acct_bal_amt, acct_bal_upd_dtm FROM aicfo_get_all_amt WHERE view_dv = '증권' AND curr_cd = 'KRW' AND acct_dv LIKE 'ELS%' AND reg_dt = '20250218'",
"SELECT bank_nm, acct_dv, acct_no, deposit_amt, total_appr_amt, acct_bal_amt, acct_bal_upd_dtm FROM aicfo_get_all_amt WHERE view_dv = '증권' AND curr_cd = 'KRW' AND acct_dv LIKE 'DLS%' AND reg_dt = '20250218'",
"SELECT view_dv, SUM(acct_bal_amt) AS total_acct_bal_amt FROM aicfo_get_all_amt WHERE view_dv IN ('수시', '대출') AND curr_cd = 'KRW' AND reg_dt = '20221215' GROUP BY view_dv",
"SELECT view_dv, SUM(acct_bal_amt) AS total_acct_bal_amt FROM aicfo_get_all_amt WHERE view_dv IN ('수시', '예적금') AND curr_cd = 'KRW' AND reg_dt = '20231021' GROUP BY view_dv",
"SELECT view_dv, SUM(acct_bal_amt) AS total_acct_bal_amt FROM aicfo_get_all_amt WHERE view_dv IN ('수시', '증권') AND curr_cd = 'KRW' AND reg_dt = '20220220' GROUP BY view_dv",
"SELECT view_dv, curr_cd, SUM(acct_bal_amt) AS total_acct_bal_amt FROM aicfo_get_all_amt WHERE view_dv IN ('수시', '증권') AND curr_cd <> 'KRW' AND reg_dt = '20240206' GROUP BY view_dv, curr_cd",
"SELECT view_dv, curr_cd, SUM(acct_bal_amt) AS total_acct_bal_amt FROM aicfo_get_all_amt WHERE view_dv IN ('대출', '증권') AND curr_cd <> 'KRW' AND reg_dt = '20240324' GROUP BY view_dv, curr_cd",
"SELECT view_dv, curr_cd, SUM(acct_bal_amt) AS total_acct_bal_amt FROM aicfo_get_all_amt WHERE view_dv IN ('예적금', '증권') AND curr_cd <> 'KRW' AND reg_dt = '20241224' GROUP BY view_dv, curr_cd",
"SELECT bank_nm, COUNT(*) AS acct_cnt, SUM(acct_bal_amt) AS total_acct_bal_amt FROM aicfo_get_all_amt WHERE view_dv = '수시' AND curr_cd = 'KRW' AND bank_nm = '신한은행' AND reg_dt = '20250218' GROUP BY bank_nm",
"SELECT bank_nm, acct_dv, acct_no, acct_bal_amt, real_amt, acct_bal_upd_dtm FROM aicfo_get_all_amt WHERE view_dv = '수시' AND acct_dv LIKE '%한도%' AND curr_cd = 'KRW' AND reg_dt = '20250218'",
"SELECT bank_nm, SUM(acct_bal_amt) AS total_acct_bal_amt, SUM(real_amt) AS total_real_amt FROM aicfo_get_all_amt WHERE view_dv = '수시' AND curr_cd = 'KRW' AND bank_nm IN('신한은행', '기업은행') AND reg_dt = '20250218' GROUP BY bank_nm",
"SELECT bank_nm, acct_dv, acct_no, acct_bal_amt, real_amt, acct_bal_upd_dtm FROM aicfo_get_all_amt WHERE view_dv = '수시' AND curr_cd = 'KRW' AND acct_dv like '%야놀자%' AND reg_dt = '20250217'",
"SELECT bank_nm, acct_dv, acct_no, acct_bal_amt, real_amt, acct_bal_upd_dtm FROM aicfo_get_all_amt WHERE view_dv = '수시' AND curr_cd = 'KRW' AND reg_dt = '20241127' AND acct_dv LIKE '%보통예금%'",
"SELECT bank_nm, acct_dv, acct_no, acct_bal_amt, real_amt, acct_bal_upd_dtm FROM aicfo_get_all_amt WHERE view_dv = '수시' AND curr_cd = 'KRW' AND reg_dt = '20240517' AND acct_dv LIKE '%보통예금%'",
"SELECT bank_nm, acct_dv, acct_no, acct_bal_amt, real_amt, acct_bal_upd_dtm FROM aicfo_get_all_amt WHERE view_dv = '수시' AND curr_cd = 'KRW' AND reg_dt = '20241102' AND acct_dv LIKE '%보통예금%'",
"SELECT bank_nm, acct_dv, acct_no, acct_bal_amt, real_amt, acct_bal_upd_dtm FROM aicfo_get_all_amt WHERE view_dv = '수시' AND curr_cd = 'KRW' AND reg_dt = '20240816' AND acct_dv LIKE '%한도대출%'",
"SELECT bank_nm, acct_dv, acct_no, acct_bal_amt, real_amt, acct_bal_upd_dtm FROM aicfo_get_all_amt WHERE view_dv = '수시' AND curr_cd = 'KRW' AND reg_dt = '20240715' AND acct_dv LIKE '%한도대출%'",
"SELECT bank_nm, acct_dv, acct_no, acct_bal_amt, real_amt, acct_bal_upd_dtm FROM aicfo_get_all_amt WHERE view_dv = '수시' AND curr_cd = 'KRW' AND reg_dt = '20240704' AND acct_dv LIKE '%한도대출%'",
"SELECT bank_nm, acct_dv, acct_no, acct_bal_amt, open_dt, due_dt, intr_rate, acct_bal_upd_dtm FROM aicfo_get_all_amt WHERE view_dv = '예적금' AND acct_dv LIKE '%적금%' AND curr_cd = 'KRW' AND reg_dt = '20200420'",
"SELECT bank_nm, acct_dv, acct_no, acct_bal_amt, open_dt, due_dt, intr_rate, acct_bal_upd_dtm FROM aicfo_get_all_amt WHERE view_dv = '예적금' AND acct_dv LIKE '%예금%' AND curr_cd = 'KRW' AND reg_dt = '20231223'",
"SELECT bank_nm, acct_dv, acct_no, acct_bal_amt, open_dt, due_dt, intr_rate, acct_bal_upd_dtm FROM aicfo_get_all_amt WHERE view_dv = '예적금' AND acct_dv LIKE '%적금%' AND curr_cd = 'KRW' AND reg_dt = '20180516'",
"SELECT bank_nm, acct_dv, acct_no, acct_bal_amt, open_dt, due_dt, intr_rate, acct_bal_upd_dtm FROM aicfo_get_all_amt WHERE view_dv = '예적금' AND acct_dv LIKE '%예금%' AND curr_cd = 'KRW' AND reg_dt = '20250211'",
"SELECT bank_nm, acct_dv, acct_no, acct_bal_amt, real_amt, acct_bal_upd_dtm FROM aicfo_get_all_amt WHERE view_dv = '수시' AND curr_cd = 'KRW' AND reg_dt = '20180313' AND acct_dv LIKE '%웹케시글로벌%' AND acct_no LIKE '%1005203820981%'",
"SELECT bank_nm, acct_dv, acct_no, acct_bal_amt, open_dt, due_dt, intr_rate, acct_bal_upd_dtm FROM aicfo_get_all_amt WHERE view_dv = '예적금' AND acct_dv LIKE '%비즈플레이%' AND curr_cd = 'KRW' AND reg_dt = '20180313'",
"SELECT bank_nm, acct_dv, acct_no, acct_bal_amt, real_amt, acct_bal_upd_dtm FROM aicfo_get_all_amt WHERE view_dv = '수시' AND curr_cd = 'KRW' AND reg_dt = '20240524' AND acct_dv LIKE '%비즈플레이%'",
"SELECT bank_nm, acct_dv, acct_no, acct_bal_amt, real_amt, acct_bal_upd_dtm FROM aicfo_get_all_amt WHERE view_dv = '수시' AND curr_cd = 'KRW' AND reg_dt = '20190522' AND acct_dv LIKE '%웹케시%'",
"SELECT bank_nm, acct_dv, acct_no, acct_bal_amt, real_amt, acct_bal_upd_dtm FROM aicfo_get_all_amt WHERE view_dv = '수시' AND curr_cd = 'KRW' AND reg_dt = '20190522' AND acct_dv LIKE '%웹케시%'",
"SELECT bank_nm, acct_dv, acct_no, acct_bal_amt, real_amt, acct_bal_upd_dtm FROM aicfo_get_all_amt WHERE view_dv = '수시' AND curr_cd = 'KRW' AND reg_dt = '20210918' AND acct_dv LIKE '%당좌%'",
"SELECT bank_nm, acct_dv, acct_no, acct_bal_amt, real_amt, acct_bal_upd_dtm FROM aicfo_get_all_amt WHERE view_dv = '수시' AND acct_dv LIKE '%기업자유예금%' AND curr_cd = 'KRW' AND reg_dt = '20240723'",
"SELECT bank_nm, acct_dv, acct_no, acct_bal_amt, real_amt, acct_bal_upd_dtm FROM aicfo_get_all_amt WHERE view_dv = '수시' AND curr_cd = 'KRW' AND reg_dt = '20240116'",
"SELECT bank_nm, acct_dv, acct_no, acct_bal_amt, real_amt, acct_bal_upd_dtm FROM aicfo_get_all_amt WHERE view_dv = '수시' AND curr_cd = 'KRW' AND acct_bal_amt >= POWER(10,8) AND reg_dt = '20230309'",
"SELECT acct_no, reg_dt, intr_rate FROM aicfo_get_all_amt WHERE view_dv = '대출' AND curr_cd = 'KRW' AND reg_dt IN ('20250218', '20250219') AND acct_no LIKE '%1512% ORDER BY reg_dt",
"SELECT bank_nm, acct_dv, acct_no, acct_bal_amt, open_dt, due_dt, intr_rate, acct_bal_upd_dtm FROM aicfo_get_all_amt WHERE view_dv = '예적금' AND curr_cd = 'KRW' AND acct_dv LIKE '%적금%' AND open_dt BETWEEN '20231201' AND '20231231' AND reg_dt = '20240928'",
"SELECT bank_nm, acct_no, deposit_amt, total_appr_amt, acct_bal_amt, acct_bal_upd_dtm FROM aicfo_get_all_amt WHERE view_dv = '증권' AND curr_cd = 'KRW' AND reg_dt = '20240302'",
"SELECT bank_nm, acct_dv, acct_no, acct_bal_amt, open_dt, due_dt, intr_rate, acct_bal_upd_dtm FROM aicfo_get_all_amt WHERE view_dv = '예적금' AND curr_cd = 'KRW' AND due_dt = '' AND reg_dt = '20250614'",
"SELECT bank_nm, acct_dv, acct_no, acct_bal_amt, real_amt, acct_bal_upd_dtm FROM aicfo_get_all_amt WHERE view_dv = '수시' AND curr_cd = 'KRW' AND reg_dt = '20231205' AND acct_dv LIKE '%예금%'",
"SELECT bank_nm, SUM(acct_bal_amt) AS total_acct_bal_amt, SUM(real_amt) AS total_real_amt FROM aicfo_get_all_amt WHERE view_dv = '예적금' AND curr_cd = 'KRW' AND reg_dt = '20240615' GROUP BY bank_nm",
"SELECT bank_nm, acct_dv, acct_no, acct_bal_amt, open_dt, due_dt, intr_rate, acct_bal_upd_dtm FROM aicfo_get_all_amt WHERE view_dv = '예적금' AND curr_cd = 'KRW' AND due_dt BETWEEN '20220921' AND '20221109' AND reg_dt = '20221109'",
"SELECT bank_nm, acct_dv, acct_no, curr_cd, acct_bal_amt, real_amt, acct_bal_upd_dtm FROM aicfo_get_all_amt WHERE view_dv = '수시' AND curr_cd <> 'KRW' AND reg_dt = '20231120'",
"SELECT bank_nm, acct_dv, acct_no, acct_bal_amt, open_dt, due_dt, intr_rate, acct_bal_upd_dtm FROM aicfo_get_all_amt WHERE view_dv = '예적금' AND curr_cd = 'KRW' AND reg_dt = '20220822'",
"SELECT bank_nm, acct_no, acct_dv, acct_bal_amt, open_dt, due_dt, intr_rate, acct_bal_upd_dtm FROM aicfo_get_all_amt WHERE view_dv = '예적금' AND curr_cd = 'KRW' AND acct_bal_amt BETWEEN (35 * POWER(10, 10) * 0.9) AND (35 * POWER(10, 10) * 1.1) AND reg_dt = '20211214'",
"SELECT bank_nm, acct_dv, acct_no, acct_bal_amt, real_amt, acct_bal_upd_dtm FROM aicfo_get_all_amt WHERE view_dv = '수시' AND curr_cd = 'KRW' AND AND reg_dt = '20190605'",
"SELECT bank_nm, acct_no, deposit_amt, total_appr_amt, acct_bal_amt, acct_bal_upd_dtm FROM aicfo_get_all_amt WHERE view_dv = '증권' AND curr_cd = 'KRW' AND reg_dt = '20230213'",
"SELECT bank_nm, acct_no, acct_dv, acct_bal_amt, open_dt, due_dt, intr_rate, acct_bal_upd_dtm FROM aicfo_get_all_amt WHERE view_dv = '대출' AND curr_cd = 'KRW' AND acct_bal_amt = 5 * POWER(10, 7) AND reg_dt = '20181121'",
"SELECT bank_nm, acct_no, deposit_amt, total_appr_amt, acct_bal_amt, acct_bal_upd_dtm FROM aicfo_get_all_amt WHERE view_dv = '증권' AND curr_cd = 'KRW' AND reg_dt = '20210509' AND acct_bal_amt = 7 * POWER(10, 7)",
"SELECT bank_nm, acct_dv, acct_no, acct_bal_amt, real_amt, acct_bal_upd_dtm FROM aicfo_get_all_amt WHERE view_dv = '수시' AND curr_cd = 'KRW' AND reg_dt = '20171219' AND acct_dv = '웹케시글로벌' AND acct_no LIKE '%1005203820982%'",
"SELECT bank_nm, acct_dv, acct_no, acct_bal_amt, real_amt, acct_bal_upd_dtm FROM aicfo_get_all_amt WHERE view_dv = '수시' AND curr_cd = 'KRW' AND reg_dt = '20191125' ORDER BY acct_bal_amt DESC LIMIT 1",
"SELECT bank_nm, acct_dv, acct_no, acct_bal_amt, open_dt, due_dt, intr_rate, acct_bal_upd_dtm FROM aicfo_get_all_amt WHERE view_dv = '대출' AND curr_cd = 'KRW' AND due_dt BETWEEN '20210401' AND '20210430' AND reg_dt = '20210407'",
"SELECT bank_nm, acct_dv, acct_no, curr_cd, acct_bal_amt, real_amt, acct_bal_upd_dtm FROM aicfo_get_all_amt WHERE view_dv = '수시' AND curr_cd <> 'KRW' AND acct_no LIKE '%9872%' AND reg_dt = '20210628'",
"SELECT bank_nm, acct_dv, acct_no, acct_bal_amt, real_amt, acct_bal_upd_dtm FROM aicfo_get_all_amt WHERE view_dv = '수시' AND curr_cd = 'KRW' AND reg_dt = '20231218'",
"SELECT bank_nm, acct_no, acct_bal_amt, real_amt, acct_bal_upd_dtm FROM aicfo_get_all_amt WHERE view_dv = '수시' AND curr_cd = 'KRW' AND reg_dt = '20190916' AND acct_bal_amt = 1 * POWER(10, 11)",
"SELECT bank_nm, acct_no, deposit_amt, total_appr_amt, acct_bal_amt, acct_bal_upd_dtm FROM aicfo_get_all_amt WHERE view_dv = '증권' AND curr_cd = 'KRW' AND reg_dt = '20240630'",
"SELECT bank_nm, acct_dv, acct_no, acct_bal_amt, real_amt, acct_bal_upd_dtm FROM aicfo_get_all_amt WHERE view_dv = '수시' AND curr_cd = 'KRW' AND reg_dt = '20200331'",
"SELECT bank_nm, acct_dv, acct_no, acct_bal_amt, real_amt, acct_bal_upd_dtm FROM aicfo_get_all_amt WHERE view_dv = '수시' AND curr_cd = 'KRW' AND reg_dt = '20230630'",
"SELECT bank_nm, acct_dv, acct_no, acct_bal_amt, open_dt, due_dt, intr_rate, acct_bal_upd_dtm FROM aicfo_get_all_amt WHERE view_dv = '예적금' AND curr_cd = 'KRW' AND reg_dt = '20230213' AND acct_dv = '비즈플레이'",
"SELECT bank_nm, SUM(acct_bal_amt) AS total_acct_bal_amt, SUM(real_amt) AS total_real_amt FROM aicfo_get_all_amt WHERE view_dv = '수시' AND curr_cd = 'KRW' AND bank_nm IN ('국민은행', '농협은행') AND reg_dt = '20210509' GROUP BY bank_nm",
"SELECT bank_nm, acct_dv, acct_no, acct_bal_amt, open_dt, due_dt, intr_rate, acct_bal_upd_dtm FROM aicfo_get_all_amt WHERE view_dv = '예적금' AND curr_cd = 'KRW' AND acct_dv LIKE '%적금%' AND open_dt BETWEEN '20191201' AND '20191231' AND reg_dt = '20200228'",
"SELECT bank_nm, acct_dv, acct_no, acct_bal_amt, open_dt, due_dt, intr_rate, acct_bal_upd_dtm FROM aicfo_get_all_amt WHERE view_dv = '대출' AND reg_dt = '20180516' AND curr_cd = 'KRW' ORDER BY due_dt ASC LIMIT 1",
"SELECT bank_nm, acct_dv, acct_no, acct_bal_amt, open_dt, due_dt, intr_rate, acct_bal_upd_dtm FROM aicfo_get_all_amt WHERE view_dv = '대출' AND reg_dt = '20170317' AND curr_cd = 'KRW' ORDER BY due_dt DSEC LIMIT 1",
"SELECT bank_nm, acct_dv, acct_no, acct_bal_amt, open_dt, due_dt, intr_rate, acct_bal_upd_dtm FROM aicfo_get_all_amt WHERE view_dv = '예적금' AND reg_dt = '20241007' AND curr_cd = 'KRW' ORDER BY due_dt ASC LIMIT 1",
"SELECT bank_nm, acct_dv, acct_no, acct_bal_amt, open_dt, due_dt, intr_rate, acct_bal_upd_dtm FROM aicfo_get_all_amt WHERE view_dv = '예적금' AND reg_dt = '20210903' AND curr_cd = 'KRW' ORDER BY due_dt DESC LIMIT 1",
"SELECT bank_nm, SUM(acct_bal_amt) AS total_acct_bal_amt, SUM(real_amt) AS total_real_amt FROM aicfo_get_all_amt WHERE view_dv = '수시' AND curr_cd = 'KRW' AND reg_dt = '20250222' GROUP BY bank_nm"
]
answers = []

# 질문과 답변을 1:1로 매칭
data = [{"question": q, "answer": ""} for q in questions]

try:
    # JSON 파일로 저장
    with open("../data/question.json", "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
    print("JSON 파일이 성공적으로 생성되었습니다.")
except Exception as e:
    print(f"오류가 발생했습니다: {e}")